### ISSUE TITLE
Improve the "Repository Trained!" modal

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#49]
**Description:**  

![image](https://user-images.githubusercontent.com/39275274/47655689-4f688180-db6c-11e8-971c-9a6d0ac3b925.png)

1. Put close button inside the modal
2. Remove this title, it's unnecessary since Languages ​​Report is the only thing we have on this modal
3. Repository Trained! > **Repository trained successfully!**
4. Put this caption below the modal title, we need to see the caption before the content
5. Show only the languages in use on the bot
6. Correct the spacing
7. It's nice to put an OK button at the end of the modal

> **Browser:** any
> **OS:** any
> **Authenticated**: any
> **URL**: https://bothub.it/...

**Comment by douglasppaz** [comment]
Task list:

- [ ] Put close button inside the modal **[Waiting for specs]**
- [ ] Remove this title, it's unnecessary since Languages ​​Report is the only thing we have on this modal
- [ ] Repository Trained! > Repository trained successfully!
- [ ] Put this caption below the modal title, we need to see the caption before the content
- [ ] Show only the languages in use on the bot
- [ ] Correct the spacing **[Waiting for specs]**
- [ ] It's nice to put an OK button at the end of the modal **[Waiting for specs]**
